### ISSUE TITLE
[Feature] Adding incremental functionality to the balance sheet

### ISSUE THREAD

**Issue by fivetran-avinash** [fivetran/dbt_netsuite#100]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

The Netsuite Balance Sheet was designed to be cumulative and capture historical transactions, which is why those records are held in each subsequent accounting period. This produces the most value for the end user as it is easy for end users to tie out values to the Netsuite Balance Sheet UI. 

However, over time, adding historical records to each accounting period increases the row count significantly (think Fibonacci sequence, where the table is growing even more widely in scale). This is leading to performance issues where tables are loading millions of historical rows that rarely change. 

Adding incremental functionality so that only the most recent rows from recent accounting periods are loaded into the balance sheet would improve performance and lead to a better customer experience, while also providing the same longstanding functionality that the initial balance sheet build was designed for..

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by jmongerlyra** [comment]
I am interested in the approach taken on this enhancement once it is decided.
