### ISSUE TITLE
[Feature] Allow downstream filtering on transaction booleans in model netsuite2__transaction_details

### ISSUE THREAD

**Issue by FrankTub** [fivetran/dbt_netsuite#113]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I would like to use model `netsuite2__transaction_details` in downstream models that I create in my own project. To do it in an efficient way I would like to be able to filter on at least the following columns.

- `is_main_line`
- `is_tax_line`
- `is_closed`

### Describe alternatives you've considered

Misuse `transaction_lines_pass_through_columns` and create your own column that is passed through.

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-reneeli** [comment]
Hi @FrankTub  thanks for opening this and highlighting your use case, in addition to opening that PR! 

We've added this to our backlog and will pick this up when our team has availability.

**Comment by FrankTub** [comment]
@fivetran-reneeli , do you have an indication on how long such a PR will take? If it takes some more time I will have to change my code setup and figure out another solution so we can meet business deadlines at our side.

**Comment by fivetran-catfritz** [comment]
Hi @FrankTub I have started working on performance updates to our Netsuite package and will fold your PR into mine. These updates will most likely be released by the end of this month. 

In the meantime you should be able to point your packages.yml to the branch that you shared in your PR, since we do not plan to release any updates between now and my next update. Let me know if you have any questions about this!

**Comment by FrankTub** [comment]
Thanks for the update @fivetran-catfritz , that will work for us.

**Comment by FrankTub** [comment]
Have added some additional fields since I want to use the model `netsuite2__transaction_details` for all sorts of downstream models and need some additional keys to do so that cannot simply be placed in your dbt project as pass through fields.

**Comment by fivetran-catfritz** [comment]
@FrankTub To update you, I am planning to merge you branch into our next release branch tomorrow. I will also push some small documentation updates to your branch before I do.

**Comment by fivetran-catfritz** [comment]
@FrankTub I have merged your changes into our next release branch to be batch released with our other updates in the coming weeks.
