### ISSUE TITLE
Questions about the To_Subsidiary fields

### ISSUE THREAD

**Issue by kenzie-marsh** [fivetran/dbt_netsuite#143]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Hi all, 

I'm not really asking for a feature here, just looking to better understand the to_subsidiary fields, how they work and what they represent. If there's already documentation please feel free to point me to it!! 

On the Netsuite UI side, it appears that using the "Subsidiary Context" filter in the UI functions similarly to using `to_subsidiary` in these dbt models. Do you know if we can assume that using To Subsidiary in these downstream models will always serve the same function as the Subsidiary Context field within Netsuite? It looks like all of the `to_subsidiary` fields are sourced from the `tosubsidiary` field on the Consolidated Exchange Rates model originally, does that mean that they always represent a currency conversion? 

Any other context or details that you have on this functionality would be helpful, I'm new to Netsuite and just getting up to speed. 

### How would you implement this feature?

I think additional documentation on this functionality would be great.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance.
- [ ] No.

### Anything else?

Thank you!

**Comment by fivetran-joemarkiewicz** [comment]
Hi @kenzie-marsh thanks for this question and hopefully we can help address these questions!

> On the Netsuite UI side, it appears that using the "Subsidiary Context" filter in the UI functions similarly to using to_subsidiary in these dbt models. Do you know if we can assume that using To Subsidiary in these downstream models will always serve the same function as the Subsidiary Context field within Netsuite?

- Unfortunately I'm not very familiar with navigating the Nestuite UI. However, when looking at [this Netsuite document](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_N2123544.html) it looks like the `to_subsidiary` field will achieve the same results. If you enable subsidiaries in this dbt model and then filter on the relevant subsidiary then I imagine you should achieve the same results as the filter provides in the UI. 

> It looks like all of the to_subsidiary fields are sourced from the tosubsidiary field on the Consolidated Exchange Rates model originally, does that mean that they always represent a currency conversion?

- Correct, the subsidiary fields will represent a currency conversion. When the subsidiary variable is enabled you will also see the [to_subsidiary_currency_symbol](https://github.com/fivetran/dbt_netsuite/blob/0300d33ad60178e5c6cc8cb450f7f4b228f7b7fe/models/netsuite2.yml#L299-L304) field which will represent the currency which the conversion is being applied from the parent currency.

We do have some brief additional details documented [here](https://github.com/fivetran/dbt_netsuite/tree/main?tab=readme-ov-file#to-subsidiary-netsuite2-only) regarding the impact and use of the Subsidiary fields when the variable is enabled. Ultimately, I do believe that you can rely on these fields to recreate the Subsidiary Context you see in the Netsuite UI. Please let me know if you find this is not the case when validating the results between the Netsuite UI filtered report and the filtered end models from this dbt package. 

Thanks!

**Comment by kenzie-marsh** [comment]
Thanks so much Joe! That should do it on answering this question. If we have any follow-ups I'll re-open this thread. Much appreciated!
