### ISSUE TITLE
Netsuite improvements

### ISSUE THREAD

**Issue by fivetran-kristin** [fivetran/dbt_netsuite#18]
- Allow for easier exploration of balance sheet & income statement transactions
- Joined data should allow for users to insert the additional columns they want (for example, if account is joined, allow users to add in account_name). perhaps this can be done through passthrough column variables.
- Explore the possibility of allowing the balance sheet to be filtered by subsidiary (would need to explore if currency for this should be converted or original transaction converted amounts, or into the subsidiary default currency).
- All models should materialize as tables for faster exploration on the BI tool side.  This is set up for the 3 final models (as of v0.2.0), but may want to consider materializing additional models as tables to address point #1 above.

**Comment by tkennedy22** [comment]
This would be a huge help. More detail is always better to help troubleshooting and make decisions. It would also be a value add to create a cumulative value for each transaction, this would present the data very similar to how balance sheet data is shown, but without duplicating many lines of the transaction_lines table. This benefit processing power of the visualization tools.  Another model could be building out more of the mapping tables that will be used in visualizations (ie Accounts table, Class table, date table). These already exist in Netsuite but have many unused fields. If the model produced a complete package with all the tables that were going to be used it would be a big help.

**Comment by tkennedy22** [comment]
Hey Kristin. As I was working through, Another comment I had was to make sure there are no nulls in the account_ID column. Teams will use that to join other fields from account dimension tables. The three items without account_ID are : cumulative Translation Adjustment, Net Income, and Retained earnings. I understand you are plugging these from Income Statement values, but having an account ID is still important. One idea is to make them negative numbers ie (-3 = Cumulative, -2 = Net Income, -3 = Retained Earnings), or you could make them a very big number 9999, or something similar. Happy to follow up for more clarity.

**Comment by fivetran-joemarkiewicz** [comment]
Marking this as `won't fix` for the time being. Our team will be working on updates in the coming months for compatibility with Netsuite2. We will take these points into consideration during the Netsuite2 updates. Thanks for this feedback and input @tkennedy22!
