### ISSUE TITLE
FEATURE - extend standard models provided by dbt

### ISSUE THREAD

**Issue by asargumed** [fivetran/dbt_netsuite#26]
**Are you a Fivetran customer?** 
Alexaner Shmidt - BI Specialist - Dialogue Argumed GmbH

**Is your feature request related to a problem? Please describe.**
We are using dbt-netsuite package, but generated transactions detail doesn’t include transaction_extid, which we are actively using for quality checks. It would be helpfull to include this column or even apply some filter to manage visibility.

**Describe the solution you'd like**
A macros or a config, which extends standard model

**Describe alternatives you've considered**
folk the the package and extend it

**Additional context**

**Please indicate the level of urgency and business impact of this request** 

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented. 
- [ ] No, I'd prefer if someone else did this.  I don't have the time and/or don't know how to incorporate the changes necessary.

**Comment by fivetran-kristin** [comment]
@asargumed thanks for the request! 

This should be an easy add. I've added this request to our workload for next sprint.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @asargumed I am picking this up for the current sprint and wanted to let you know that we currently have some **major** updates to the netsuite package that will be included with this update.

I will notify you here when I have the completed working branch ready for you to test with this feature also included.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @asargumed 👋 

I am excited to let you know we have been able to the ability for pass through columns to be used in the netsuite models! As I mentioned, this most recent release (which will most likely be live on the hub tomorrow) has had some major changes. The most relevant change being that the netsuite package is now built off our [dbt_netsuite_source](https://github.com/fivetran/dbt_netsuite_source) package which generates staging models that the final models reference.

If you would like to include the `transaction_extid` in your final netsuite models then you may use the below variable config within your `dbt_project.yml` to pass the field through to the final model.
```yml
vars:
  transactions_pass_through_columns: ['transaction_extid']
```
Let me know if you have any questions when installing the latest version (`v0.3.0`) of the package and if you have any problems adding the pass through column to your models!

**Comment by asargumed** [comment]
Hey @fivetran-joemarkiewicz,

Thank you so much.

I will upgrade the packages and let you know, if Im expieriencing any issues.
Best regards,
Alexander
