### ISSUE TITLE
QUESTION - Removed fields with 0.4.0

### ISSUE THREAD

**Issue by Norina-Sun** [fivetran/dbt_netsuite#33]
**Are you a Fivetran customer?** 
Norina Sun, Senior Data Analyst, Dialogue 

**Your Question**
with the new package version the fields `customer_external_id` was removed from `netsuite__transaction_details` and `subsidiary_name` was removed from `netsuite__income_statement`

**Additional context**
We need them for our modelling

**Please indicate the level of urgency and business impact of this request** 
we can't update to dbt 20 until these fields are available again

I added them back locally + tested & everything is fine, if you want I could open a pr for the changes

**Comment by fivetran-joemarkiewicz** [comment]
Hi @Norina-Sun! 

Thanks for opening this question, that is very interesting as to why these were removed. I do not see a reason as to why these would not be included especially since the join is still included in the latest release. If you have been able to add these fields back in on your branch it would be great if you could open a PR!

Let me know if you have any questions with opening a PR. Thanks again.

**Comment by Norina-Sun** [comment]
Hi @fivetran-joemarkiewicz thanks for the quick response. I need to make changes on here and dbt-netsuite-source, but I don't think I have permissions to create a branch on either. I read the contributor guide but am I missing something?

**Comment by fivetran-joemarkiewicz** [comment]
You should be able to create a fork of the repo and open a PR once you have made changes to the fork.

**Comment by Norina-Sun** [comment]
Whoops yeah realized I forgot to fork the repo once I hit comment sorry!

**Comment by fivetran-joemarkiewicz** [comment]
Thanks so much @Norina-Sun! I most likely won't get around to reviewing these until the start of next week. I will let you know if I have any questions. Thanks!

**Comment by Norina-Sun** [comment]
Hi @fivetran-joemarkiewicz ! Just wanted to check in and see if you were still going to review it this week? My sprint ends on Friday so I wanted to know if I should move the task out since its externally blocked. :)

**Comment by fivetran-joemarkiewicz** [comment]
Hi @Norina-Sun this is still on my task list for this week! I will give it a review today and let you know if I have any questions. Thanks!

**Comment by fivetran-joemarkiewicz** [comment]
@Norina-Sun thanks again for helping us improve the latest version of this package by incorporating the fields that were inadvertently removed in a previous upgrade ⭐ 

I have just cut a release for the `v0.4.1` version of the netsuite package which adds the fields (plus a few others that got lost in the upgrade) to the package. This will most likely be released to the [dbt hub](https://hub.getdbt.com/fivetran/netsuite/latest/) at the top of the hour.

Please feel free to comment back in this ticket or open a new one if you have any other questions or requests.
