### ISSUE TITLE
FEATURE - Explore Incremental or More Performant Models

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_netsuite#39]
**Are you a Fivetran customer?** 

Fivetran created PR. However, I would greatly appreciate any users of the Netsuite package to post their thoughts or comments in this thread if you would like to contribute to the discussion. 😃 

**Is your feature request related to a problem? Please describe.**
 
The `transactions` and `transaction_lines` source tables have an exponentially larger data volume than the other tables within the Netsuite source. It seems that this (in addition to complex transformations within the intermediate models) that the models take longer than desired run times. 

It would be worth exploring this package further to investigate these performance lags and what can be done to improve the runtime for users. My thoughts are to maybe apply incremental logic to models involving the `transactions` and `transaction_lines` models since their volume could be impacting performance. Regardless I would like to dig deeper into this.

**Describe the solution you'd like**
 
The runtime of the Netsuite models are greatly shortened and optimized.

**Describe alternatives you've considered**
 
The normal run will sometimes take a long time to materialize. No alternatives have been explored yet.

**Additional context**

It does seem to only get hung up on the models involving the transactions. I _think_ this is where we need to focus our efforts.

**Please indicate the level of urgency and business impact of this request** 

Low urgency.

**Comment by nabinn** [comment]
I am trying to use the dbt_netsuite package on our Snowflake data warehouse.
The models `netsuite__balance_sheet` and `netsuite__income_statement` are materialized in few minutes but the third model `netsuite__transaction_details` takes a really long time to materialize. 
I tried this multiple times. Once it ran for almost 8 hours without creating the table. I am using a separate `X-small` warehouse instance dedicated to running the dbt job.

Please see the logs if it is useful.
[console.log](https://github.com/fivetran/dbt_netsuite/files/8180718/console.log)
[dbt.log](https://github.com/fivetran/dbt_netsuite/files/8180719/dbt.log)

**Comment by fivetran-joemarkiewicz** [comment]
Thanks so much @nabinn for adding to the conversation on the performance of the transaction_detail model! We really appreciate you sharing these logs as well. Our team is looking into improving the performance of this model and will share updates and continue to collaborate in this thread.

**Comment by bmayer99** [comment]
I agree the model could be made incremental. 
however, since updates on transactions and transaction_lines are common occurrence in NetSuite, the logic would need to upsert records based on the  `last_modified_date` attribute.

**Comment by fivetran-jamie** [comment]
Before we try out incremental stuff (though you're totally right @bmayer99), I noticed that all of the intermediate models (which are pretty complicated and reference large tables like `transaction_lines` on their own) are all materialized ephemerally. 3 of the incremental models feed into a fourth, `int_netsuite__transactions_with_converted_amounts`, which is referenced by all of the end models. 

so i've pushed a branch that materializes `int_netsuite__transactions_with_converted_amounts` (and not the other intermediate models) as a non-ephemeral table. super curious how that affects runtime for y'all @nabinn @bmayer99 if you'd like to try running the following branch of the package:

```yml
# your packages.yml file
packages:
  - git: https://github.com/fivetran/dbt_netsuite.git
    revision: feature/optimize-transactions
    warn-unpinned: false
```


alternatively, if the above doesn't make a substantial difference (or if `int_netsuite__transactions_with_converted_amounts` ends up taking way too long itself?), i'm wondering how materializing the entire intermediate layer non-ephemerally would change things up:
```yml
# your dbt_project.yml file
models:
  netsuite:
    intermediate:
      materialized: table
```

**Comment by bmayer99** [comment]
@fivetran-jamie @fivetran-joemarkiewicz given the shift to netsuite2.com data source, is it worth optimizing the current models or focus on supporting the new source?

**Comment by fivetran-jamie** [comment]
that's a very good point, and we do have plans to explore shifting to netsuite2 in the future. in the meantime though, would you mind trying out the above configurations to see if anything improves on your end?

**Comment by bmayer99** [comment]
I can see an almost 50% execution time improvement on the query run time of models 
`netsuite__income_statement`
`netsuite__transaction_details`
`netsuite__balance_sheet`

our NetSuite instance is still pretty light in terms of data volume so it does not impact our overall runtime by that much 
(7% execution time improvement on `dbt run --select +netsuite`)

**Comment by fivetran-jamie** [comment]
interesting -- was that after setting the entire `intermediate` folder to materialize as tables, or just the `int_netsuite__transactions_with_converted_amounts` model?

**Comment by bmayer99** [comment]
in my case, the total run time (`dbt run --select +netsuite`) is the same for either option.

**Comment by fivetran-jamie** [comment]
cool, then it's probably ideal to just materialize the one problematic model as a table, which can actually be achieved via your `dbt_project.yml` file: 

```yml
models:
  netsuite:
    intermediate:
      int_netsuite__transactions_with_converted_amounts: 
        +materialized: table
```

in the coming months we'll be updating the package to work with netsuite2 and will **heavily** take performance into consideration while developing. given this, we won't be exploring performance optimizations with the current state of the package any further. 

thus, i'll be marking this as `won't fix` for the time being as folks should refer to the above config until we roll out netsuite2 compatibility

**Comment by fivetran-jamie** [comment]
had an office hours call where the above materialization config didn't improve things for the user. currently the transaction details model takes 4 hours to run for them 😬 @fivetran-joemarkiewicz maybe it's time to reopen this

**Comment by fivetran-catfritz** [comment]
Hi @bmayer99 and @nabinn, in the case either of you are still interested in this issue, I've made a test branch with incremental end models. If you'd like to test it out, you can install the following branch:
```yml
packages:
  - git: https://github.com/fivetran/dbt_netsuite.git
    revision: feature/performance-improvements
    warn-unpinned: false
```

For Snowflake, I aimed to optimize for a shorter runtime since my understanding is that Snowflake charges based on time as opposed to data scanned, but let me know if you have any comments on that!

**Comment by fivetran-catfritz** [comment]
Hi @bmayer99 and @nabinn, the performance updates have been released with the latest version of this package. Below is the snipped to install this latest version.
```yml
packages:
  - package: fivetran/netsuite
    version: [">=0.13.0", "<0.14.0"]
```
I am closing this issue, but if you have any additional comments or questions, feel free to reach out to us here.
