### ISSUE TITLE
[Bug] Fivetran dbt netsuite2__transaction_details table doesn't exactly sum up to match Netsuite.com Income Statement

### ISSUE THREAD

**Issue by wwilliamsnuwest** [fivetran/dbt_netsuite#51]
***EDIT***: I believe I've found the initial problem (but not the root cause yet): For the Income discrepancy between Netsuite.com and dbt Netsuite2, Account #41100 is NOT being included in the dbt Fivetran data like it is in the Netsuite data. I wonder if this is a result of us both having a parent account rollup called 41100 in Netsuite as well as a (missing in dbt Netsuite2) 'child' 41100 account...

I will look to see if this is the same issue in the Expenses discrepancy. Please hold off spending any time on my issue until I do more homework on my end!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The Fivetran dbt netsuite2__transaction_details table when summed up in Snowflake SQL by me to create what I assume SHOULD match the Netsuite.com Income Statement page does not match 100%. Instead, it's like ~99%, and I can't figure out the differences or what logic/data might be different.

For example, here's a summary of our Revenue, Cogs, and Expenses from Netsuite's page: Income Statement for a Period I'll call 'Period A' for privacy (with some digits clipped for privacy as well):

![image](https://user-images.githubusercontent.com/100794323/194397781-bcab8d47-eff4-4741-8f5b-9ce19d5f3bf6.png)

And here's my SQL query that is attempting to replicate the same result using the dbt netsuite2__transaction_details table (I can't use income_statement because that table has only 7 rows in it per a different bug I just filed today):

`SELECT CASE account_type_name WHEN 'Income' THEN '1 - Income' WHEN 'Cost of Goods Sold' THEN '2 - COGS' WHEN 'Expense' THEN '3 - Expense' ELSE account_type_name END AS account_type_name_sorted,

 SUM(transaction_amount) AS transaction_amount, 
COUNT(transaction_line_id) AS num_trans_line_ids

FROM dbt_db.dbt_prod_netsuite.netsuite2__transaction_details 

WHERE account_type_name IN ('Expense', 'Income', 'Other Expense', 'Other Income', 'Cost of Goods Sold') -- These are the only accounts I believe I want in order to just get Income Statement items.
AND DATE(transaction_date) BETWEEN [period A start date and period A end date]
 GROUP BY 1
ORDER BY 1`

And here are the results of that Snowflake query. You can see that they're mostly very close, but for some reason not exact as I would expect:
![image](https://user-images.githubusercontent.com/100794323/194397921-f5dba941-3456-49d3-bb95-36f8674a00b8.png)

### Expected behavior

I would expect my SQL logic to result in numbers that match the Netsuite.com Income Statement totals.

### dbt Project configurations

Netsuite2. I don't think anything else is relevant, but please tell me if you need more detail here.

### Package versions

I last ran dbt deps to update my Netsuite package around mid-September 2022 in my dev environment, which are the variables shown below. However, for prod, dbt deps is run daily, and prod is where the numbers I've used above are coming from.

The netsuite package package.yml:
packages:
- package: fivetran/netsuite_source
  version: [">=0.5.0", "<0.6.0"]

My main packages.yml:
packages:
  - package: fivetran/netsuite
    version: [">=0.6.0", "<0.7.0"]

### What database are you using dbt with?

snowflake

### dbt Version

I'm using dbt cloud and dbt --version doesn't appear to be a valid command. Not sure how to get you this or if it's not applicable w/ cloud.

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by wwilliamsnuwest** [comment]
Here's a breakdown by parent account from Netsuite:
![image](https://user-images.githubusercontent.com/100794323/194400879-430336bb-b235-41c1-acae-b7da71556861.png)


And from Snowflake using the same logic as shown above:
![image](https://user-images.githubusercontent.com/100794323/194400971-0c03fa22-86d1-4165-8869-28396dbba64f.png)

**Comment by fivetran-joemarkiewicz** [comment]
Hi @wwilliamsnuwest thanks so much for the detailed write-up. It does look like the results are ~99% match to what you are seeing in Netsuite. I have a few ideas that we could look into:
- I am not sure what your period start and end dates are from your query. Are these dates all in the past? I would just want to confirm that there is not a possibility that there isn't a data latency issue on our hands (ie. data created today hasn't been synced in the warehouse yet).
- I would be curious to know more details around that single account (41100) you mentioned. Are you saying there are two accounts in your Netsuite instance with the same account number? Additionally, do you know if the total values for that account for the specified period equate to the delta in the end calculation?

**Comment by wwilliamsnuwest** [comment]
Yeah, well in the past, like the latest one was at least a couple months ago. I actually think that account # issue was a red herring, apologies, since I noticed in other months there are multiple accounts that are off by a little, AND that that account DOES show up in other months.

I wonder if this is actually related to the same date issue that seems relevant to reversals. This is a wild shot in the dark, but I wonder if there's a timezone problem going on. Like, maybe Netsuite records things without time zones and is PST (our local time), and then perhaps Fivetran thinks these transaction dates are in UTC, or something like that. I noticed that there's no hourly/minute detail (everything's ending in 00:00:000) associated with the netsuite2__transaction_details transaction_date (which is actually a timestamp) field.

That said, I changed my Netsuite.com default timezone to UTC, and saw the same Income Statement figures in Netsuite.com, but of course, who knows if they 'honor' a user's local timezone selection when figuring the date range of the transactions, or if timestamps are even assigned at all by our users/Netsuite when transactions are logged.

Best,
Ward
________________________________

**Comment by wwilliamsnuwest** [comment]
I don't know if an update to either the dbt Netsuite2 or the Fivetran Netsuite2 connector was released to fix this issue, BUT, with the exception of one single transaction that I'm still having issue with (shown in another issue I opened here), this appears to have been resolved!
