### ISSUE TITLE
[Bug] Reversed transaction not showing up as same date that Netsuite Income Statement records it

### ISSUE THREAD

**Issue by wwilliamsnuwest** [fivetran/dbt_netsuite#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

We have a transaction reversal that is causing a weird issue. When I look in Snowflake's dbt Netsuite2 netsuite2__transaction_details, there's -$8.2 M Income charge from two transactions both on 1/1/2022 with Dec 2021 totals of $47 M and Jan 2022 of $58 M. 

`
SELECT CASE account_type_name WHEN 'Income' THEN '1 - Income' WHEN 'Cost of Goods Sold' THEN '2 - COGS' WHEN 'Expense' THEN '3 - Expense' ELSE account_type_name END AS account_type_name_sorted,

:datebucket(DATE(transaction_date)) AS transaction_date_bucket, -- Grouping by Month in Snowflake filter not shown

 SUM(transaction_amount) AS transaction_amount

FROM dbt_db.dbt_prod_netsuite.netsuite2__transaction_details 
WHERE account_type_name IN ( 'Income')

AND DATE(transaction_date) BETWEEN '2021-12-01' AND '2022-01-31'

 GROUP BY 
  1,2
 ORDER BY 
 1,2
`
Query above to get these monthly totals in Snowflake:
![image](https://user-images.githubusercontent.com/100794323/194433253-79ac42d3-6265-474a-af19-4b2317879419.png)

Query to isolate the $4.1 M charges:
`SELECT CASE account_type_name WHEN 'Income' THEN '1 - Income' WHEN 'Cost of Goods Sold' THEN '2 - COGS' WHEN 'Expense' THEN '3 - Expense' ELSE account_type_name END AS account_type_name_sorted,
account_number,
parent_account_name,
transaction_date,
transaction_amount, 
transaction_line_id

FROM dbt_db.dbt_prod_netsuite.netsuite2__transaction_details 
WHERE account_type_name IN ('Expense', 'Income', 'Other Expense', 'Other Income', 'Cost of Goods Sold')

AND DATE(transaction_date) = '2022-01-01' 
AND account_number = 45100
`

![image](https://user-images.githubusercontent.com/100794323/194432445-af1eb8ba-c1c6-487d-b023-9d15c161bbca.png)
You can see above that there's actually TWO $4.1 M charges, but both are on 1/1/2022. I think instead what should have happened was to have one applied to 12/31/2022 (the date of thing being reversed, if I understand what Netsuite.com is showing) and one apply to 1/1/2022. At least that would make the two months in Snowflake = the two months' totals in Netsuite.com when summing in Snowflake by transaction_date.

![image](https://user-images.githubusercontent.com/100794323/194431743-ba0c3c87-059f-417a-a94a-c0bf0c41847a.png)

However, in Netsuite.com on the Income Statement page, that transaction appears to be split between 12/31/2022 and 1/1/2022, resulting in monthly Dec 2021 totals of $47 M and Jan 2022 of $58 M:
![image](https://user-images.githubusercontent.com/100794323/194431676-111944ff-f34e-4119-9f9d-90e9335bb428.png)

Here's the transaction records from Netsuite showing a +$4.1 M on 12/31/2022 and a -$4.1 M on 1/1/2022:
![image](https://user-images.githubusercontent.com/100794323/194431346-ab6460c7-a334-444e-870d-9ebe29681e80.png)

### Expected behavior

I'd expect the monthly totals to match in Netsuite.com vs Snowflake, but instead they don't.

### dbt Project configurations

Nothing important to add here. 

### Package versions

packages:
  - package: fivetran/netsuite
    version: [">=0.6.0", "<0.7.0"]

### What database are you using dbt with?

snowflake

### dbt Version

Not sure if this is relevant since I'm using dbt cloud.

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for opening this issue @wwilliamsnuwest and for your detailed investigation into the issue.

An interesting piece of this puzzle is that the transaction_date (which seems to incorrectly represent the transaction and its reversal) is not modified within our dbt package. You can see it is selected from the staging table (which is a direct query from the source transactions table synced by Fivetran). 
https://github.com/fivetran/dbt_netsuite/blob/c1fe30ec1b1164679e74bfbf03ec605e00ebc400/models/netsuite2/netsuite2__transaction_details.sql#L87

I would be curious to understand why the data being synced is not accurately reflecting the date of the reversal. If I am understanding your bug report correctly, if we address the one of the two records to take place on 12/31 then it should resolve the issue (please correct me if I am wrong). 

If the above is the case, I think this may be a [Fivetran Support](https://support.fivetran.com/hc/en-us) related inquiry and should be investigated at the connector level. Happy to chat more if you feel the transformation is causing this instead.

**Comment by wwilliamsnuwest** [comment]
Gotcha. Yeah, it does seem like it's the issue you're describing where perhaps the reversal needs to have a transaction date of the date of the ORIGINAL transaction being 'reversed' (12/31/2021) vs the date of the reversal (1/1/2022).

If this is a Fivetran connector issue, do I need to open up a separate ticket with them, or are you able to do that on my behalf?

Thanks!
Ward
________________________________

**Comment by fivetran-reneeli** [comment]
Hey @wwilliamsnuwest ! If the problem seems to be within the connector itself, we encourage customers to open a ticket to support on their end! However feel free to link this issue. I reckon engineering will tag us in the ticket.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @wwilliamsnuwest I will close this issue as it should be addressed within the connector itself. If you were unable to create the support ticket, you can create one [here](https://support.fivetran.com/hc/en-us).

If you feel this GitHub issue should remain open, feel free to comment here and we can reopen if needed. 😄
