### ISSUE TITLE
[Databricks Adapter Support] Request for Databricks as a destination support for Netsuite package

### ISSUE THREAD

**Issue by mitchquarfot** [fivetran/dbt_netsuite#55]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Similar to the ad_reporting and salesforce pre-built dbt packages, we have a customer, [Thoughtspot](https://fivetran.lightning.force.com/lightning/r/Opportunity/0061G00000OrmGKQAZ/view), requesting Databricks support for our Netsuite package.

### Describe alternatives you've considered

I'd be glad to shadow/assist with the development process in any way I can, but my dbt knowledge is not yet at a point where I feel like I could build this out myself.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [X] No.

**Comment by mitchquarfot** [comment]
Hey @fivetran-joemarkiewicz! Thanks for the update on this! I think that'll be huge for us as more and more prospects start implementing Databricks as a layer in their stack. Just to clarify, the Netsuite package did end up working on a Databricks destination, so we may just need to update our docs for that model.

**Comment by fivetran-jamie** [comment]
in latest release!
