### ISSUE TITLE
Missing table NETSUITE_SUITEANALYTICS.ACCOUNTINGPERIOD: Error Creating stg_netsuite2__accounting_periods_tmp.sql

### ISSUE THREAD

**Issue by jaredx435k2d0** [fivetran/dbt_netsuite#64]
When running dbt run -s netsuite, I'm getting
```
Database Error in model stg_netsuite2__accounting_periods_tmp (models/netsuite2/tmp/stg_netsuite2__accounting_periods_tmp.sql
002003 (42S02): SQL compilation error:
Object '[MY_DB_NAME].NETSUITE_SUITEANALYTICS.ACCOUNTINGPERIOD' does not exist or not authorized.
```

In my dbt_project.yml vars, I have
`netsuite_data_model: netsuite2 #netsuite by default`

We are using the NetSuite SuiteAnalytics connector, configured to use NetSuite2.com. I just re-synced the connector, and we actually don't have that table.

The closest thing we have name wise is ACCOUNTINGPERIODFISCALCALENDARS.

I'm not sure if I'm maybe just missing something simple here. What would cause my project to expect this table that the connector doesn't create?

**Comment by jaredx435k2d0** [comment]
This prevents all of the final models from building.

**Comment by fivetran-jamie** [comment]
hey there! yeah the netsuite dbt package definitely expects this table to exist, as it is leveraged heavily in our intermediate models (ie [here](https://github.com/fivetran/dbt_netsuite/blob/main/models/netsuite2/intermediate/int_netsuite2__tran_and_reporting_periods.sql)).

very curious about your netsuite use case, as i was the under the impression everyone had accounting periods 🤔  in the `ACCOUNTINGPERIODFISCALCALENDARS` table, is the `accountingperiod` field completely null?

**Comment by jaredx435k2d0** [comment]
Interesting.

The accountingperiod field is populated for me for every record in the ACCOUNTINGPERIODFISCALCALENDARS table.

**Comment by fivetran-jamie** [comment]
interesting... i wonder if y'all are explicitly not syncing the accounting period table. could you check this in the `schema` tab of your netsuite connector in the fivetran UI?

**Comment by jaredx435k2d0** [comment]
We don't have it as an available table:

<img width="856" alt="image" src="https://user-images.githubusercontent.com/111536894/219768512-7d7fbc27-7897-4543-b7bc-5cf023210800.png">

And just to confirm, I do have "NetSuite2.com (BETA)" selected as my "Data Source" in the Connector Setup screen.

**Comment by jaredx435k2d0** [comment]
Turns out this was a permissions issue; the NetSuite side was preventing Fivetran was getting this table. We adjusted those permissions and the table is now there. I'm waiting for the sync to finish to verify that the models now work well.

**Comment by fivetran-jamie** [comment]
ah great to hear! lmk when you've finished verifying

**Comment by jaredx435k2d0** [comment]
I think we're all set! Final models seemed to build just fine.
Sorry for the false alarm.
