### ISSUE TITLE
Question: How are `_FIVETRAN_DELETED` rows handled

### ISSUE THREAD

**Issue by jaredx435k2d0** [fivetran/dbt_netsuite#65]
We use Snowflake as our destination.

I've noticed that there are rows where `_FIVETRAN_DELETED` is sometimes marked as TRUE.

How is this handled in the data model? Are these records still used in calculations? If so, is there a config option somewhere I can change to filter them all out? Using [dbt-coves](https://github.com/datacoves/dbt-coves), I remove all these records in my other staging schemas for other sources.

**Comment by fivetran-jamie** [comment]
hey there! so we left these in here (in some places) in case a soft-deleted entity was still referenced as a foreign key in another table (ie an `account` was deleted but is still the stored `account_id` in transaction tables -- you'd still want the non-null account info

**Comment by fivetran-jamie** [comment]
(ignore the brief closing, accidentally clicked 'close') 😅

**Comment by jaredx435k2d0** [comment]
Roger that!
Thank you.
