### ISSUE TITLE
[Feature] Ability to disable consolidated exchange rate tables

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_netsuite#71]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Some Netsuite users do not operate in multiple currencies and therefore do not need to leverage the consolidated exchange rates tables. Unfortunately, the current build of the Netsuite and Netsuite2 data models within this package are dependent on these upstream tables.

For instances where customers do not (or are not yet currently) operating in multiple currencies, we should explore including the ability to disable these models if needed or desired.

### Describe alternatives you've considered

There are currently no strong alternatives other than creating an empty table that fits the desired schema and running the empty table in the package.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

### Anything else?

We may be able to leverage the `union_data` macro from Fivetran Utils to create an empty table if the source is not found. This may be useful since customers may not know when they begin to operate in multiple currencies. We should do more research to validate this.

For any user that has come across this FR and would like to see it implemented, please either comment or react to this message. This will allow our team at Fivetran to properly prioritize this feature for future implementation.

**Comment by bdegroot-teamsvc** [comment]
I did build an empty table with fields based off of the netsuite definition of that table but it looks the like package is relying on the table to multiply all base amounts. The null currency conversion amounts causes all fields in the end models as null.
https://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2017_2/script/record/consolidatedexchangerate.html
Thanks!
Ben

**Comment by fivetran-avinash** [comment]
Hi @bdegroot-teamsvc ! We believe we have deployed a fix that should have resolve any issues you might have with this package. Let us know how it goes!

**Comment by bdegroot-teamsvc** [comment]
@fivetran-avinash Thanks so much, this saved us weeks of work! I started testing the minute I saw that merge notification come through and so far all looks good. Appreciate everything your team is working on!
