### ISSUE TITLE
[Bug] <dedup netsuite2__transaction_details tables>

### ISSUE THREAD

**Issue by rwang-lyra** [fivetran/dbt_netsuite#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

currently there is duplication in the table `netsuite2__transaction_details`,   the root cause seems to be in the process of sql:
1. when calling `int_netsuite2__consolidated_exchange_rates`
2. while `int_netsuite2__consolidated_exchange_rates` has no dups, but using only a subset of its columns may introduce duplicated records.

### Relevant error log or model output

```shell
select transaction_id, transaction_line_id, COUNT(1)
from <db_holder>.<schema_holder>.netsuite2__transaction_details
group by transaction_id, transaction_line_id
having count(1) >1
order by 3 DESC;
```

### Expected behavior

The above query returns zero result

### dbt Project configurations

N/A

### Package versions

packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0
  - package: dbt-labs/dbt_project_evaluator
    version: 0.5.0
  - package: dbt-labs/dbt_external_tables
    version: 0.8.3
  - package: fivetran/netsuite
    version: 0.8.0

### What database are you using dbt with?

snowflake

### dbt Version

snowflake: 1.4.2 

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @rwang-lyra thanks for opening this issue. It sounds like you are experiencing duplicates in the transaction details end model for Netsuite2. I also appreciate you performing some initial scoping of where the issue may be occurring. 

However, I am not fully understanding the relationship of the duplicates to the `int_netsuite2__consolidated_exchange_rates` intermediate model? Additionally, in the query you shared above you mention how it results in 0 records. Wouldn't that mean there are no duplicates in the transaction details end model?

Would you be able to share a bit more regarding the duplicates you are seeing. If you are comfortable, it would be extremely helpful to provide some screenshots (sensitive data omitted) or examples of the duplicates you see in your data. This will help us understand the anti-behavior and what we may need to triage within the package to resolve an issue.

**Comment by rwang-lyra** [comment]
Hi Joe,  thanks for responding - sorry if part of the description is unclear.  Please see my comments below

> I am not fully understanding the relationship of the duplicates to the int_netsuite2__consolidated_exchange_rates intermediate model? 

`int_netsuite2__consolidated_exchange_rates` is an upstream dataset for  `netsuite2__transaction_detail`s.  I tracked it down [here](https://github.com/fivetran/dbt_netsuite/blob/main/models/netsuite2/intermediate/int_netsuite2__acctxperiod_exchange_rate_map.sql#L20-L23) from compile code. basically this cte has duplicates already, unless we do a distinct on the list of relevant columns only. happy to provide a PR if that helps(tried to submit but got declined)

> Additionally, in the query you shared above you mention how it results in 0 records. Wouldn't that mean there are no duplicates in the transaction details end model?

for the query in "Relevant error log or model output" section, I would expect it returns zero results as there should be no duplications, however it is now returning results as the duplication exists in netsuite2__transaction_details table

> If you are comfortable, it would be extremely helpful to provide some screenshots (sensitive data omitted) or examples of the duplicates you see in your data.

attached a screenshot here that shows the existences of dups in netsuite2__transaction_details
![image](https://github.com/fivetran/dbt_netsuite/assets/124346025/323a6973-961a-4ee4-b73e-427e1d07da1b)

**Comment by fivetran-joemarkiewicz** [comment]
@rwang-lyra thanks for providing the extra detail, this is very helpful in understanding the issue you are experiencing. 

After your previous message I was able to identify what may be the result of this duplication. Upon inspecting and expanding the results of the `int_netsuite2__consolidated_exchange_rates` model, I realized the join we have is what is bringing in the duplicates.

https://github.com/fivetran/dbt_netsuite/blob/9761bf48c222704ca1da8aacfcd3cf9c05a043ab/models/netsuite2/intermediate/base/int_netsuite2__consolidated_exchange_rates.sql#L22-L23

Upon inspecting this intermediate model and the raw tables, I realized the duplication is because this results in multiple `accounting_book_id`s. In fact, I realized that the raw `consolidated_exchange_rate` (which this model is essentially pulling from) includes an `accounting_book_id` key that we can join on to resolve these duplicates. I actually was able to get a quick fix on a branch that applies this update. If you have availability, would you be open to testing this branch to see if it resolves the duplicates?

You can test this branch by using the following in place of your netsuite package referencing in your packages.yml
```yml
  - git: https://github.com/fivetran/dbt_netsuite.git
    revision: bugfix/consolidate-exch-account-book-add
    warn-unpinned: false 
```

Let me know if this resolves the error you are seeing!

**Comment by rwang-lyra** [comment]
Thanks @fivetran-joemarkiewicz for the quick fix! Running tests - looks like there is one more thing to be added here in dbt_modules/netsuite_source/models/netsuite2/src_netsuite2.yml 
otherwise I'm getting compaints on `CONSOLIDATED_EXCHANGE_RATES.ACCOUNTING_BOOK` being an invalid identifier.

![image](https://github.com/fivetran/dbt_netsuite/assets/124346025/6263c9bb-4172-440c-9fd9-d4a052982811)

**Comment by rwang-lyra** [comment]
Sure! see below for `packages.yml`:
```packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0
  - package: brooklyn-data/dbt_artifacts
    version: 2.3.0
  - package: dbt-labs/dbt_project_evaluator
    version: 0.5.0
  - package: dbt-labs/dbt_external_tables
    version: 0.8.3
  - git: https://github.com/fivetran/dbt_netsuite_source.git
    revision: bugfix/consolidate-exch-accounting-book-id
    warn-unpinned: false
```
also I found with this branch of dbt_netsuite_source, Im having trouble dbt run netsuite models. looked into target folder, seems netsuites models are missing there - please see attached.

![image](https://github.com/fivetran/dbt_netsuite/assets/124346025/c8ce10a1-0f3c-4fbd-8f3f-c241252dc0bb)

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for sharing @rwang-lyra! It looks like you included `dbt_netsuite_source` in the packages.yml config. However, you will want this to be `dbt_netsuite` instead. Can you try the below config in place of what you currently have? (Note, the only difference is we are pointing to dbt_netsuite instead of dbt_netsuite_source). 

```yml
packages:
  - git: https://github.com/fivetran/dbt_netsuite.git
    revision: bugfix/consolidate-exch-account-book-add
    warn-unpinned: false 
```

**Comment by rwang-lyra** [comment]
@fivetran-joemarkiewicz  yep that was it -  I copied over from the packages.yml on your branch without noticing the different there.  I just fixed the lib and looks like it builds and makes no more dups!

**Comment by fivetran-joemarkiewicz** [comment]
Great I am glad to hear that worked!! I know we are planning to release an update to our Netsuite package in the next day or so. I may not be able to incorporate this update within that release, but you should be able to see this update live within the week. 😄 

Be sure to follow this thread to stay up to date on when the changes will be made live. Thanks again for raising this and working with us to resolve the issue!

**Comment by rwang-lyra** [comment]
Thanks @fivetran-joemarkiewicz, yeah definitely will stay tuned for this fix to be in the next release.

on a side note, my team also reported dups in `netsuite2__balance_sheet` - I didn't get to investigate on the root cause, wonder if I should just raise it here, or would it best be a new issue instead?

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for letting us know! I think it would be safe to raise that issue here as the dupes may be somewhat related and will allow us to take our time and investigate/resolve with your initially observed issue.

Additionally, as I was looking into the fix I shared in the WIP branch (adding the new join condition to remove the duplicates). I actually realized the entire `int_netsuite2__consolidated_exchange_rates` model is no longer needed as the intention of this model is to bring in the `accounting_book_id`; however, since this is now already available in the staging model for consolidated_exchange_rates, we can just bring it in from the source and avoid this model entirely! 

On the note of the dupes found within `netsuite2__balance_sheet`, feel free to share more details and we can look into scoping the issue and identifying possible causes and resolutions.

**Comment by rwang-lyra** [comment]
sure. glad to hear we can make the compute process more concise.

below query shows dups in `netsuite2__balance_sheet` if you can take a look
```
select transaction_id, transaction_line_id, COUNT(*)
from  **.**..netsuite2__balance_sheet
group by transaction_id, transaction_line_id
having count(1) > 1
order by 3 desc;
```

**Comment by fivetran-joemarkiewicz** [comment]
Hi @rwang-lyra thanks for sharing the query which highlights dups you are seeing. I was able to look into this a bit on my own and wanted to call out that the grain of the balance_sheet end model is a bit more granular than `transaction_id` and `transaction_line_id`. It also includes the `accounting_period_id` and the `account_name`. See the full grain test here

https://github.com/fivetran/dbt_netsuite/blob/8d6a122d5a03bf578606d3a4da191331fb4c1d81/models/netsuite2.yml#L55-L61

Do you see duplicates for this combination?

**Comment by rwang-lyra** [comment]
Thanks for the reply. good to learn! I've updated the query and run again - however there is still dups found on this granularity, see my query below:L
```
select transaction_id, transaction_line_id, accounting_period_id, account_name, COUNT(*)
from   **.**.netsuite2__balance_sheet
group by transaction_id, transaction_line_id, accounting_period_id, account_name
having count(1) > 1
order by 3 desc;
```

**Comment by rwang-lyra** [comment]
additional context re above query: the dup rows seems to diff on account_type_name, account_id, account_number and balance_sheet_sort_helper - for one of the two records, there are null account_id and account_name

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for sharing, I am not seeing duplicates with the above query with our data but I appreciate you sharing more context around the differences you are seeing. Would you possibly be comfortable providing an example of one of these duplicate cases? I am particularly interested in the null account_id and name.

**Comment by fivetran-reneeli** [comment]
Hi @rwang-lyra! We're working on this fix during our current sprint. Was gonna bump Joe's ^ question as well, it would be concerning if any record has a null account_id 🤔  

I can understand adding `account_id` to the unique test that combines `transaction_id`, `transaction_line_id`, `accounting_period_id`, `account_name`, but want to think through the rest. Any info you have would be greatly appreciated 🙏

**Comment by fivetran-reneeli** [comment]
Also, @rwang-lyra , if it's easier to hop on a [call](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours ), just let us know 😄

**Comment by rwang-lyra** [comment]
Hi @fivetran-reneeli  sorry for the late reply as I have been occupied by other priorities.   For the issues with `netsuite2__balance_sheet`, there are two findings that I would like to add:
1. this granularity shows a lot of dups if they are meant to be unique
```
select transaction_id, transaction_line_id, accounting_period_id, account_name, COUNT(*)
from    d*.*.netsuite2__balance_sheet
group by transaction_id, transaction_line_id, accounting_period_id, account_name
having count(1) > 1
order by 5 desc;
```
2. my team also reported a possibly relevant issue, here I quote:

```
NETSUITE2__BALANCE_SHEET is applying incorrect consolidated translation rate. Example is below however the issue applies to transactions in many other accounts.

Generate Rate Type on the COA is set to Historical. Based on this, the result of the query below should be $x USD. However, it returns $y  USD.

The reason is because the Dec 2021 transaction is translating at the Jun 2023 Historical Rate, rather than the Dec 2021 Historical Rate. 

Transaction in accounts set to translate at Historical Rates should refer back to the rate in the period they were recorded. In this case, that is Dec 2021.

```

**Comment by rwang-lyra** [comment]
not sure if it's helpful for reproducing.  possibly I can hop on a call next week when my time is more flexible

**Comment by fivetran-reneeli** [comment]
Thanks for the details @rwang-lyra! 

1. Yeah, it is concerning that you are seeing dupes for that grain in the balance sheet. I think it's a good idea to hop on a call next week and dig into it-- https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours

2. Re: translation rates-- this seems to be something that's outside the issue of dupes. It would be best for you to open a separate ticket for this with the same level of detail you've added for this issue! That way my team and I can take a look in our upcoming sprints 🙏

**Comment by rwang-lyra** [comment]
Thanks @fivetran-reneeli  I've booked a slot at office hours this week. 
Will open a separate issue re translation rates

**Comment by fivetran-reneeli** [comment]
Thanks @rwang-lyra! Speak to you soon!

**Comment by fivetran-reneeli** [comment]
Thanks for opening this ticket re: transaction details de-duping! We have included this fix in our latest release of the package, linked below. As such we'll be closing this!

[v0.8.1 dbt_netsuite](https://github.com/fivetran/dbt_netsuite/releases/tag/v0.8.1)
