### ISSUE TITLE
[Urgent] New Version Range does not contain current package version

### ISSUE THREAD

**Issue by hadihamed** [fivetran/dbt_netsuite#76]
https://github.com/fivetran/dbt_netsuite/blob/81c822e5ec964f36c0536c312176c8189a687ca1/packages.yml#L3C2-L3C2

The current package for netsuite_source is 0.6.3 and does not fall within these bounds, resulting in failures in dbt_deps

**Comment by fivetran-reneeli** [comment]
Hi @hadihamed , the correct dependencies should be live now, so will be closing this. Let me know if you run into anything else!
