### ISSUE TITLE
[Feature] enable for multiple books support for Consolidated Exchange rate

### ISSUE THREAD

**Issue by rwang-lyra** [fivetran/dbt_netsuite#86]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Context
Our Netsuiite has two books enabled: primary and adjustment. The adjustment book includes all transactions on primary + additional transactions. That relationship between books is noted in the database by the fields is_primary and adjustment_only.
![image](https://github.com/fivetran/dbt_netsuite/assets/124346025/ae49a8a0-3a80-43a1-a082-5d97d11f3d7a)

Issue :
Consolidated exchange rates are also by book which impacts the values in converted_amount. In the final datasets we would expect to see two lines (one primary, one adjustment) for each transaction recorded to the primary book, translated at the relevant consolidated exchange rate.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by jmongerlyra** [comment]
@rwang-lyra We can close this issue as completed.
