### ISSUE TITLE
[Feature] Update `intercompany` categorization

### ISSUE THREAD

**Issue by fivetran-catfritz** [fivetran/dbt_netsuite#87]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Currently, `netsuite2__transaction_details` considers an account as intercompany if the account name contains the word “intercompany”. Reviewing the netsuite documentation (see [here](https://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2016_1/schema/record/account.html) and [here](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_N1475891.html#Making-Intercompany-Journal-Entries)) and per internal discussion, we should be using the `eliminate` column from the source account table. 

We will need to:
1. Bring in `eliminate` column to `stg_netsuite2__accounts` (also should check on netsuite if this applies)
2. Use `eliminate` to determine `is_account_intercompany` flag. The source uses the letters `T` and `F` (well our source does, so maybe consider if it can also come in as boolean), so convert to boolean in transform.

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by jmongerlyra** [comment]
I agree with this approach.

**Comment by jmongerlyra** [comment]
What's the timeline on this fix? It is actually needed in our environment for all three models.

**Comment by fivetran-joemarkiewicz** [comment]
@jmongerlyra we will plan to include this update in the next major release of netsuite. We are waiting to validate the results with our internal finance team before rolling them out.

I expect by the end of our current sprint (10/18) we are hoping to have all updates rolled out to the next version of the Netsuite package.

**Comment by fivetran-joemarkiewicz** [comment]
This feature has been incorporated in the latest release of the dbt_netsuite and dbt_netsuite_source packages. These updates should be live at the top of the hour.
