### ISSUE TITLE
[Bug] Base book transactions missing on adjustment-only books 

### ISSUE THREAD

**Issue by jmongerlyra** [fivetran/dbt_netsuite#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

In order to match NetSuite reporting, adjustment-only books should have all transactions from the base book present and translated at the adjustment book's consolidated exchange rates.

### Relevant error log or model output

```shell
No error logs. The models require additional logic.
```

### Expected behavior

Base book transactions should be replicated on the related adjustment-only book and translated at the book specific consolidated exchange rates.

### dbt Project configurations

See related PR. https://github.com/fivetran/dbt_netsuite/pull/90

### Package versions

packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0
  - package: brooklyn-data/dbt_artifacts
    version: 2.3.0
  - package: dbt-labs/dbt_project_evaluator
    version: 0.5.0
  - package: dbt-labs/dbt_external_tables
    version: 0.8.3
  - package: fivetran/netsuite
    version: 0.10.0

### What database are you using dbt with?

snowflake

### dbt Version

1.4.5

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-catfritz** [comment]
Hi @jmongerlyra thank you for submitting this issue and the PR! I will be working on this and will probably have some questions for you in the coming days.

**Comment by jmongerlyra** [comment]
@fivetran-catfritz Sounds good! @fivetran-joemarkiewicz has my contact info if a meeting is beneficial.

**Comment by fivetran-catfritz** [comment]
Hi @jmongerlyra. I have a version of the branch that should be close to final! Would you be able to test it out to make sure any updates I made still produce the results you expect? You can install it using this snippet:

```yml
- git: https://github.com/fivetran/dbt_netsuite.git
  revision: bug/multibook-subsidiary-updates
  warn-unpinned: false
```

Also, I opted to make the addition of the accounting book and to subsidiary info disabled by default, mainly because it could result in a large, unexpected increase of row counts for users when they upgrade versions. So now, you'll need to add the below vars to your `dbt_project.yml` to enable it. I'd like to know if that's working alright or any feedback you have as well!
```yml
vars:
  netsuite2__using_to_subsidiary: true
  netsuite2__multibook_accounting_enabled: true
```

Thanks again!

**Comment by jmongerlyra** [comment]
Thanks! I'll try to test before the end of the week. When do you need feedback?

**Comment by jmongerlyra** [comment]
@fivetran-catfritz I went ahead and tested. Looks good!

**Comment by fivetran-catfritz** [comment]
Hi @jmongerlyra thank you so much for trying that out so quickly! Stoked that it worked out for you. We will be getting this ready as a pre-release hopefully in the next week.

**Comment by fivetran-catfritz** [comment]
Hi @jmongerlyra and @rwang-lyra! We have released these updates as a beta. The test branch from before should still work, but you can now install the beta using:
```yml
packages:
  - package: fivetran/netsuite
    version: 0.12.0-b1
```
